export type SearchOperation = "arriendo" | "venta";

export type SearchListing = {
  id: string;
  code: string;
  operation: SearchOperation;
  kind: "Apartamento" | "Casa" | "Oficina";
  zone: string;
  city: string;
  address: string;
  priceLabel: string;
  priceValue: number;
  area: string;
  areaM2: number;
  rooms: number;
  baths: number;
  parking: number;
  floor?: string;
  pets: boolean;
  furnished: boolean;
  adminFee?: string;
  image: string;
  gallery: string[];
  lat: number;
  lng: number;
  description: string;
};

export const searchListings: SearchListing[] = [
  {
    id: "chico-renta",
    code: "L-1108",
    operation: "arriendo",
    kind: "Apartamento",
    zone: "Chicó",
    city: "Bogotá",
    address: "Calle 94 · Chicó Norte",
    priceLabel: "$ 8.900.000",
    priceValue: 8900000,
    area: "95 m²",
    areaM2: 95,
    rooms: 2,
    baths: 2,
    parking: 1,
    floor: "Piso 8",
    pets: true,
    furnished: false,
    adminFee: "$ 980.000",
    image: "/media/listing-chico-living-hd.png",
    gallery: [
      "/media/listing-chico-living-hd.png",
      "/media/listing-chico-kitchen-hd.png",
      "/media/listing-chico-bedroom-hd.png",
    ],
    lat: 4.6758,
    lng: -74.0482,
    description: "Apartamento luminoso con balcón, acabados premium y acceso rápido a la 7ma.",
  },
  {
    id: "salitre-renta",
    code: "L-5205",
    operation: "arriendo",
    kind: "Apartamento",
    zone: "Salitre",
    city: "Bogotá",
    address: "Av. El Dorado · Ciudad Salitre",
    priceLabel: "$ 6.500.000",
    priceValue: 6500000,
    area: "78 m²",
    areaM2: 78,
    rooms: 2,
    baths: 2,
    parking: 1,
    floor: "Piso 5",
    pets: false,
    furnished: false,
    adminFee: "$ 680.000",
    image: "/media/listing-salitre-terrace-a-hd.png",
    gallery: [
      "/media/listing-salitre-terrace-a-hd.png",
      "/media/listing-salitre-living-hd.png",
      "/media/listing-salitre-terrace-b-hd.png",
    ],
    lat: 4.6705,
    lng: -74.1012,
    description: "Incluye administración. Terraza privada y vista abierta al occidente.",
  },
  {
    id: "castellana-renta",
    code: "L-3310",
    operation: "arriendo",
    kind: "Apartamento",
    zone: "La Castellana",
    city: "Bogotá",
    address: "Calle 95 · La Castellana",
    priceLabel: "$ 3.700.000",
    priceValue: 3700000,
    area: "62 m²",
    areaM2: 62,
    rooms: 1,
    baths: 2,
    parking: 1,
    floor: "Piso 10",
    pets: true,
    furnished: true,
    adminFee: "$ 520.000",
    image: "/media/listing-salitre-living-hd.png",
    gallery: ["/media/listing-salitre-living-hd.png", "/media/listing-chico-kitchen-hd.png"],
    lat: 4.6752,
    lng: -74.0688,
    description: "Ideal para ejecutivo. Amoblado, cerca a TransMilenio y zonas gastronómicas.",
  },
  {
    id: "rosales-renta",
    code: "L-4412",
    operation: "arriendo",
    kind: "Apartamento",
    zone: "Rosales",
    city: "Bogotá",
    address: "Carrera 5 · Rosales",
    priceLabel: "$ 7.200.000",
    priceValue: 7200000,
    area: "88 m²",
    areaM2: 88,
    rooms: 2,
    baths: 2,
    parking: 1,
    floor: "Piso 4",
    pets: true,
    furnished: false,
    adminFee: "$ 890.000",
    image: "/media/listing-facade-rosales-v2.png",
    gallery: ["/media/listing-facade-rosales-v2.png", "/media/listing-chico-bedroom-hd.png"],
    lat: 4.6569,
    lng: -74.0531,
    description: "Edificio boutique en Rosales, con portería 24h y zonas comunes.",
  },
  {
    id: "cabrera-renta",
    code: "L-5518",
    operation: "arriendo",
    kind: "Apartamento",
    zone: "La Cabrera",
    city: "Bogotá",
    address: "Calle 85 · La Cabrera",
    priceLabel: "$ 9.800.000",
    priceValue: 9800000,
    area: "110 m²",
    areaM2: 110,
    rooms: 3,
    baths: 3,
    parking: 2,
    floor: "Piso 12",
    pets: true,
    furnished: false,
    adminFee: "$ 1.150.000",
    image: "/media/listing-facade-la-cabrera-v2.png",
    gallery: ["/media/listing-facade-la-cabrera-v2.png", "/media/listing-chapinero-v2-living-hd.png"],
    lat: 4.6654,
    lng: -74.0476,
    description: "Amplio, con estudio y dos parqueaderos. Vista hacia los cerros.",
  },
  {
    id: "chico-norte-renta",
    code: "L-1188",
    operation: "arriendo",
    kind: "Apartamento",
    zone: "Chicó Norte",
    city: "Bogotá",
    address: "Calle 100 · Chicó Norte",
    priceLabel: "$ 5.400.000",
    priceValue: 5400000,
    area: "70 m²",
    areaM2: 70,
    rooms: 2,
    baths: 1,
    parking: 1,
    floor: "Piso 6",
    pets: false,
    furnished: false,
    adminFee: "$ 640.000",
    image: "/media/listing-facade-chico-reservado-v2.png",
    gallery: ["/media/listing-facade-chico-reservado-v2.png", "/media/listing-chico-living-hd.png"],
    lat: 4.6821,
    lng: -74.0465,
    description: "Excelente relación precio-ubicación sobre la Calle 100.",
  },
  {
    id: "usaquen-renta",
    code: "L-6620",
    operation: "arriendo",
    kind: "Casa",
    zone: "Usaquén",
    city: "Bogotá",
    address: "Carrera 7 · Usaquén",
    priceLabel: "$ 12.500.000",
    priceValue: 12500000,
    area: "180 m²",
    areaM2: 180,
    rooms: 4,
    baths: 3,
    parking: 2,
    pets: true,
    furnished: false,
    adminFee: "$ 750.000",
    image: "/media/listing-chapinero-v2-bedroom-hd.png",
    gallery: ["/media/listing-chapinero-v2-bedroom-hd.png", "/media/listing-chapinero-v2-kitchen-hd.png"],
    lat: 4.6955,
    lng: -74.0308,
    description: "Casa remodelada cerca al centro histórico de Usaquén, con patio interior.",
  },
  {
    id: "cedritos-renta",
    code: "L-7731",
    operation: "arriendo",
    kind: "Apartamento",
    zone: "Cedritos",
    city: "Bogotá",
    address: "Calle 140 · Cedritos",
    priceLabel: "$ 4.200.000",
    priceValue: 4200000,
    area: "68 m²",
    areaM2: 68,
    rooms: 2,
    baths: 2,
    parking: 1,
    floor: "Piso 3",
    pets: true,
    furnished: false,
    adminFee: "$ 480.000",
    image: "/media/listing-chico-kitchen-hd.png",
    gallery: ["/media/listing-chico-kitchen-hd.png", "/media/listing-salitre-living-hd.png"],
    lat: 4.7182,
    lng: -74.0345,
    description: "Apartamento práctico cerca a colegios, parques y comercio de la 140.",
  },
  {
    id: "chapinero-venta",
    code: "L-2312",
    operation: "venta",
    kind: "Apartamento",
    zone: "Chapinero",
    city: "Bogotá",
    address: "Calle 63 · Chapinero Alto",
    priceLabel: "$ 1.850.000.000",
    priceValue: 1850000000,
    area: "120 m²",
    areaM2: 120,
    rooms: 3,
    baths: 2,
    parking: 2,
    floor: "Piso 12",
    pets: true,
    furnished: false,
    adminFee: "$ 1.250.000",
    image: "/media/listing-chapinero-v2-living-hd.png",
    gallery: [
      "/media/listing-chapinero-v2-living-hd.png",
      "/media/listing-chapinero-v2-kitchen-hd.png",
      "/media/listing-chapinero-v2-bedroom-hd.png",
    ],
    lat: 4.6486,
    lng: -74.0628,
    description: "Apartamento amplio con vista a los cerros y acabados actualizados.",
  },
  {
    id: "chico-venta",
    code: "L-1190",
    operation: "venta",
    kind: "Apartamento",
    zone: "Chicó",
    city: "Bogotá",
    address: "Calle 93 · Chicó",
    priceLabel: "$ 1.420.000.000",
    priceValue: 1420000000,
    area: "95 m²",
    areaM2: 95,
    rooms: 2,
    baths: 2,
    parking: 1,
    floor: "Piso 9",
    pets: true,
    furnished: false,
    adminFee: "$ 980.000",
    image: "/media/listing-chico-kitchen-hd.png",
    gallery: ["/media/listing-chico-kitchen-hd.png", "/media/listing-chico-living-hd.png"],
    lat: 4.6741,
    lng: -74.0498,
    description: "Inversión sólida en una de las zonas con mayor demanda de arriendo.",
  },
  {
    id: "rosales-venta",
    code: "L-4488",
    operation: "venta",
    kind: "Apartamento",
    zone: "Rosales",
    city: "Bogotá",
    address: "Carrera 6 · Rosales",
    priceLabel: "$ 2.150.000.000",
    priceValue: 2150000000,
    area: "140 m²",
    areaM2: 140,
    rooms: 3,
    baths: 3,
    parking: 2,
    floor: "Piso 7",
    pets: true,
    furnished: false,
    adminFee: "$ 1.450.000",
    image: "/media/listing-chico-bedroom-hd.png",
    gallery: ["/media/listing-chico-bedroom-hd.png", "/media/listing-facade-rosales-v2.png"],
    lat: 4.6582,
    lng: -74.0544,
    description: "Espacios generosos, terraza y dos parqueaderos independientes.",
  },
  {
    id: "salitre-venta",
    code: "L-5299",
    operation: "venta",
    kind: "Apartamento",
    zone: "Salitre",
    city: "Bogotá",
    address: "Av. El Dorado · Salitre",
    priceLabel: "$ 780.000.000",
    priceValue: 780000000,
    area: "78 m²",
    areaM2: 78,
    rooms: 2,
    baths: 2,
    parking: 1,
    floor: "Piso 11",
    pets: false,
    furnished: false,
    adminFee: "$ 720.000",
    image: "/media/listing-salitre-terrace-b-hd.png",
    gallery: ["/media/listing-salitre-terrace-b-hd.png", "/media/listing-salitre-living-hd.png"],
    lat: 4.6688,
    lng: -74.0985,
    description: "Oportunidad cerca al aeropuerto y a corredores empresariales.",
  },
  {
    id: "castellana-venta",
    code: "L-3391",
    operation: "venta",
    kind: "Apartamento",
    zone: "La Castellana",
    city: "Bogotá",
    address: "Calle 100 · La Castellana",
    priceLabel: "$ 920.000.000",
    priceValue: 920000000,
    area: "85 m²",
    areaM2: 85,
    rooms: 2,
    baths: 2,
    parking: 1,
    floor: "Piso 14",
    pets: true,
    furnished: false,
    adminFee: "$ 850.000",
    image: "/media/listing-chapinero-v2-kitchen-hd.png",
    gallery: ["/media/listing-chapinero-v2-kitchen-hd.png", "/media/listing-chapinero-v2-living-hd.png"],
    lat: 4.6768,
    lng: -74.0702,
    description: "Torre reciente con gimnasio, coworking y sala de juntas.",
  },
  {
    id: "cabrera-venta",
    code: "L-5580",
    operation: "venta",
    kind: "Apartamento",
    zone: "La Cabrera",
    city: "Bogotá",
    address: "Calle 86 · La Cabrera",
    priceLabel: "$ 2.480.000.000",
    priceValue: 2480000000,
    area: "160 m²",
    areaM2: 160,
    rooms: 4,
    baths: 3,
    parking: 2,
    floor: "Piso 15",
    pets: true,
    furnished: false,
    adminFee: "$ 1.680.000",
    image: "/media/listing-chapinero-v2-bedroom-hd.png",
    gallery: ["/media/listing-chapinero-v2-bedroom-hd.png", "/media/listing-facade-la-cabrera-v2.png"],
    lat: 4.6642,
    lng: -74.0461,
    description: "Penthouse-like: terraza, cuarto de servicio y acabados de alta especificación.",
  },
  {
    id: "usaquen-venta",
    code: "L-6644",
    operation: "venta",
    kind: "Casa",
    zone: "Usaquén",
    city: "Bogotá",
    address: "Calle 119 · Usaquén",
    priceLabel: "$ 1.980.000.000",
    priceValue: 1980000000,
    area: "210 m²",
    areaM2: 210,
    rooms: 4,
    baths: 4,
    parking: 3,
    pets: true,
    furnished: false,
    adminFee: "$ 890.000",
    image: "/media/listing-facade-chico-reservado-v2.png",
    gallery: ["/media/listing-facade-chico-reservado-v2.png", "/media/listing-chico-living-hd.png"],
    lat: 4.6988,
    lng: -74.0321,
    description: "Casa de tres niveles con jardín, BBQ y cuarto de huéspedes.",
  },
  {
    id: "cedritos-venta",
    code: "L-7755",
    operation: "venta",
    kind: "Apartamento",
    zone: "Cedritos",
    city: "Bogotá",
    address: "Calle 147 · Cedritos",
    priceLabel: "$ 650.000.000",
    priceValue: 650000000,
    area: "72 m²",
    areaM2: 72,
    rooms: 2,
    baths: 2,
    parking: 1,
    floor: "Piso 8",
    pets: true,
    furnished: false,
    adminFee: "$ 580.000",
    image: "/media/listing-salitre-living-hd.png",
    gallery: ["/media/listing-salitre-living-hd.png", "/media/listing-chico-kitchen-hd.png"],
    lat: 4.7225,
    lng: -74.0362,
    description: "Apartamento listo para habitar, con balcón y parqueadero cubierto.",
  },
];

export function listingsFor(operation: SearchOperation) {
  return searchListings.filter(item => item.operation === operation);
}
